### ISSUE TITLE
make hyper link in index.php

### ISSUE THREAD

**Issue by chellanivaibhav** [anonymous043044/startup-bvp1.1#14]
in file  http://localhost/startup-bvp1.1/signup/index.php replace the button "new users" with a hyerlink like this

"New Users REGISTER HERE ." where register here takes then to php/signup.php
for reference see here https://github.com/login.

**Comment by bansaltush** [comment]
done

**Comment by bansaltush** [comment]
not done ,,, i will do it at  night
